version: "3.5"

services:
  ruby:
    build:
      context: ./docker/ruby
      args:
        USERNAME: ${USERNAME-vscode}
        USER_UID: ${USER_UID-1000}
        USER_GID: ${USER_GID-1000}
        TIME_ZONE: ${TIME_ZONE-UTC}
        LOCALE: ${LOCALE-C}
    tty: true
    volumes:
      - ../:/var/task
    working_dir: /var/task
